In [1]:
# Day 8

In [2]:
# PANDAS
# 관계형 혹은 레이블로 된 데이터를 쉽고 직관적으로 작업할 수 있도록 설계된 빠르고 유연한 데이터 구조를 제공하는
# python 패키지

In [3]:
# * 주요특징
#   -  데이터 조작을 위한 DataFrame 객체지원
#   -  인메모리 데이터 구조와 csv, txt, excel, sql과 같은 다양한 형태 지원
#   -  시계열과 비 시계열 데이터를 같이 다룰 수 있는 데이터 구조 제공
# Finance, Neuroscience, Economics, Statics, Advertising, Web Analytics와 같은 다양한 분야에서 사용

In [1]:
### Pandas 자료구조 ###
# Series(1차원)와 DataFrame(2차원) 자료구조(Object)가 존재
# - Numpy Array를 기반으로 함
# - 다차원 배열(ndarray)을 위해 설계된 Numpy와 다르게 "2차원 데이터 구조에 특화"
# - Numpy 1차원 배열의 경우 행 우선이지만 Pandas 시리즈의 경우 "열우선"
# - Numpy 배열을 Index로 위치만 오지만 Pandas의 경우 이름(문자)도 올 수 있음
# - DataFrame은 여러 개의 Series를 Key(칼럼명)으로 접근하는 구조로 Dictionary와 유사

In [2]:
%%capture
!pip install pandas

In [3]:
import pandas as pd

In [4]:
# Series
# : Pandas의 기본 객체이며 1차원 배열
#   Series() 함수를 사용

In [5]:
# < 문법 >
# pandas.Series(values=[], index=[])
# - Series 생성 시 index 매개변수를 이용하여 이름 지정 가능
# - index 매개변수를 이용할 때 데이터의 개수와 인덱스의 개수는 동일해야 함
# * 다양한 데이터 타입 섞어서 사용하는 경우
#   범위가 더 큰 타입의 숫자로
#   Series에 다양한 데이터 타입의 데이터로 생성시 object 타입으로 생성

In [8]:
series = pd.Series([1,2,3])
series

0    1
1    2
2    3
dtype: int64

In [9]:
# index 지정
series = pd.Series([1,2,3], index=['A','B','C'])
series

A    1
B    2
C    3
dtype: int64

In [10]:
series.values, series.index

(array([1, 2, 3]), Index(['A', 'B', 'C'], dtype='object'))

In [11]:
s = pd.Series([1,2.5,3,4.5])
s

0    1.0
1    2.5
2    3.0
3    4.5
dtype: float64

In [14]:
# 데이터 타입 object
s = pd.Series([1,50, 'hello', '월드', 7.5])
s

0        1
1       50
2    hello
3       월드
4      7.5
dtype: object

In [15]:
# DataFrame 생성
# - 표와 같은 스프레드시트 형식의 2차원 자료 구조(row, column으로 구성)
# - DataFrame() 함수를 사용
# < 문법 >
# pandas.DataFrame(values=[], index=[], columns=[])
# -> 각 column은 서로 다른 데이터 타입을 가질 수 있음

In [16]:
dataframe = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
dataframe

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
dataframe = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],
                         index = ['A','B','C'],
                         columns = ['X1','X2','X3'])
dataframe

   X1  X2  X3
A   1   2   3
B   4   5   6
C   7   8   9

In [ ]:
# Series와 DataFrame생성 시 사용되는 데이터는 리스트, 배열뿐만 아니라 딕셔너리도 올 수 있음.
# - Series의 경우 key가 행 인덱스로 지정(index)
# - DataFrame의 경우 key가 열 인덱스로 지정(columns)

In [19]:
ser = pd.Series({'A':[1,2,3], 'B':[1,2,3]})
ser

A    [1, 2, 3]
B    [1, 2, 3]
dtype: object

In [20]:
df = pd.DataFrame({'A':[1,2,3], 'B':[2,3,4]})
df

   A  B
0  1  2
1  2  3
2  3  4

In [ ]:
# Pandas 입출력
# : 다양한 데이터 파일 유형을 읽어오거나 해당 유형으로 저장할 수 있음
# : https://pandas.pydata.org/docs/user_guide/io.html 에서 확인 가능
#   - csv 파일 읽기/저장     : read_csv / to_csv
#   - excel 파일 읽기/저장   : read_excel/to_excel

In [ ]:
# csv 파일 저장
# : index 를 False로 지정하면 index를 저장하지 않음
#   인코딩 형식을 지정할 수 있음(기본값은 'utf-8')

In [21]:
data = [['A',3,1,'X'], ['A',1,2,'X'], ['A',0,5,'Y'],
        ['B',1,6,'X'], ['B',7,2,'Y'], ['B',3,3,'X'],
        ['C',2,4,'X'], ['C',1,1,'Y'], ['C',0,2,'X']]
df = pd.DataFrame(data, columns=['A','B','C','D'])
df

   A  B  C  D
0  A  3  1  X
1  A  1  2  X
2  A  0  5  Y
3  B  1  6  X
4  B  7  2  Y
5  B  3  3  X
6  C  2  4  X
7  C  1  1  Y
8  C  0  2  X

In [ ]:
df.to_csv('data1.csv')
df.to_csv('data2.csv', index=False) #행의 0,1,2,3,4,5.. 인덱스가 안나오게 저장

In [ ]:
# csv파일 읽기
# - 파일의 형식이 'utf-8'이 아닌 경우 인코딩(encoding)형식을 지정해야 함
# - 열과 열을 구분하는 구분자가 콤마(,)가 아닌 경우 "구분자(sep")을 지정해야 함
# - 데이터가 너무 커 분할해서 데이터 로드 시 chuncksize 매개변수를 활용하여 설정 가능

In [ ]:
pd.read_csv('data1.csv')

In [ ]:
pd.read_csv('data2.csv')

In [ ]:
for df in pd.read_csv('data2.csv', chunksize=3): # 세개씩 끊어서 새로운 표로 보여줌.
    display(df)

In [ ]:
chunk = pd.read_csv('data2.csv', chunksize=3, skiprows=0) # 위와 같은 효과로 세개씩 끊어 보여줌.
chunk.get_chunk()
chunk.get_chunk()
chunk.get_chunk()

In [22]:
# Excel 파일 저장
# - index를 False로 지정하면 index를 저장하지 않음
# - sheet_name을 통해 시트명 지정 가능
# - 여러개의 시트를 저장하리 위해서는 ExcelWriter를 이용

In [24]:
df = pd.read_csv('data2.csv')
df

i

In [ ]:
df.to_excel('data1.xlsx')

In [ ]:
writer = pd.ExcelWriter('data2.xlsx')
df.to_excel(writer, sheet_name='SHEET1',index=False)
df.to_excel(writer, sheet_name='SHEET2')
df.to_excel(writer, sheet_name='SHEET3')
writer.close()

In [ ]:
# Excel 파일 읽기
# : sheet_name을 통해 읽어올 시트를 지정 가능
#   - sheet_name을 통해 특정 시트의 데이터만 가지고 올 수 있음
#   - sheet_name=None으로 지정되면, 모든 시트를 가지고 오며, 
#     시트명을 key로 시트데이터를 values로 가지는 사전 형태로 읽어 옴

In [ ]:
pd.read_excel('data2.xlsx') # 첫번째만 가져옴

In [ ]:
temp = pd.read_excel('data2.xlsx', sheet_name=None) # sheet별로 딕셔너리 형태로 모두 출력
temp

In [26]:
temp['SHEET1'] # 딕셔너리 형태이기 때문에 key 값으로 가져올 수 있다.

i

In [ ]:
### Pandas 자료구조 속성
# Series와 DataFrame에서도 속성을 통해 편리하게 조회할 수 있음.
#     ndim      :    데이터의 차원
#     shape     :    각 차원의 크기
#     values    :    해당 oject의 값
#     index     :    해당 oject의 행 인덱스
#    columns    :    해당 object의 열 인덱스
#       T       :    해당 object를 전치시킨 결과
#     dtype     :    특정 컬럼의 데이터 타입 조회
#    dtypes     :    데이터프레임의 모든 컬럼의 데이터 타입 조회

In [27]:
series = pd.Series([[1,2,3],[2,3,4]], index=['A','B'])
series

A    [1, 2, 3]
B    [2, 3, 4]
dtype: object

In [28]:
series.ndim # 1차원

1

In [29]:
series.shape # (2,)

(2,)

In [30]:
series.index

Index(['A', 'B'], dtype='object')

In [31]:
series.values

array([list([1, 2, 3]), list([2, 3, 4])], dtype=object)

In [ ]:
# series.columns # Series는 열(column이 없기 때문에 error)

In [32]:
dataframe = pd.DataFrame([[1,'a'],[2,'b'],[3,'a']], columns=['A','B'])
dataframe

   A  B
0  1  a
1  2  b
2  3  a

In [33]:
dataframe.ndim # 2차원

2

In [34]:
dataframe.shape #(3,2)

(3, 2)

In [35]:
dataframe.values

array([[1, 'a'],
       [2, 'b'],
       [3, 'a']], dtype=object)

In [36]:
dataframe.index

RangeIndex(start=0, stop=3, step=1)

In [37]:
dataframe.columns

Index(['A', 'B'], dtype='object')

In [38]:
dataframe['A'].dtype, dataframe['B'].dtype

(dtype('int64'), dtype('O'))

In [40]:
dataframe.dtypes

A    object
B    object
dtype: object

In [39]:
dataframe['A'] = ['a','a','a'] # 특정 컬럼을 통해 값 수정 가능
dataframe

   A  B
0  a  a
1  a  b
2  a  a

In [ ]:
# index와 columns 속성은 값을 조회하는 것 뿐만 아니라 값을 수정하는 것도 가능함
# 수정하고자 하는 데이터 개수와 대입하는 "데이터 개수가 동일"해야 함

In [42]:
df = pd.DataFrame({'A':[1,2,3], 'B':[2,3,4]})
df

   A  B
0  1  2
1  2  3
2  3  4

In [ ]:
# 컬럼명을 (['ㄱ','ㄴ'])로 변경
df.columns = ['ㄱ','ㄴ']
df

In [ ]:
df.index = ['A', 'B', 'C']
df

In [ ]:
# Pandas 연산
# : Pandas에서의 연산은 Numpy와 동일하게 element wise 연산
#   [row][col]이 동일한 (인덱스가 동일한) 요소끼리 연산

In [41]:
x1 = pd.Series([1,2,3,4])
y1 = pd.Series([5,6,7,8])
x1 - y1

0   -4
1   -4
2   -4
3   -4
dtype: int64

In [43]:
x2 = pd.DataFrame([[1,2],[3,4]])
y2 = pd.DataFrame([[5,6],[7,8]])
x2 + y2

    0   1
0   6   8
1  10  12

In [ ]:
# element wise 연산 시 위치가 기준이 아닌 인덱스를 기준으로 함
# 중첩되는 인덱스가 없는 경우 결과 값이 NaN으로 설정됨
# DataFrame의 경우 행 인덱스뿐만 아니라 열인덱스도 일치해야 계산이 가능함

In [44]:
x1 = pd.Series([1,2,3,4], index=['A','B','C','D'])
y1 = pd.Series([5,6,7,8], index=['B','C','D','E'])
x1 + y1

A     NaN
B     7.0
C     9.0
D    11.0
E     NaN
dtype: float64

In [45]:
x2 = pd.DataFrame([[1,2],[3,4]], index=['A', 'B'])
y2 = pd.DataFrame([[5,6],[7,8]])
x2 + y2

    0   1
A NaN NaN
B NaN NaN
0 NaN NaN
1 NaN NaN

In [46]:
x2 = pd.DataFrame([[1,2],[3,4]], columns=['A', 'B'])
y2 = pd.DataFrame([[5,6],[7,8]])
x2 + y2

    A   B   0   1
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN

In [ ]:
# 인덱싱과 슬라이싱
# Pandas Series 인덱싱과 슬라이싱
# - Numpy Array에서 사용한것과 동일하게 대괄호([])를 사용하여 특정 요소에 접근할 수 있음
# - 단, 위치가 아니라 행 인덱스를 사용한다는 점을 유의
# - -1로 가장 마지막 요소에 접근 불가

In [47]:
series = pd.Series([1,2,3,4,5])
# 첫번쨰 항목 선택
series[0]

1

In [48]:
# 두번째부터 세번째 항목 선택
series[1:3]

1    2
2    3
dtype: int64

In [49]:
# 마지막 항목 선택
series[4]

5

In [ ]:
# 문자열 인덱스 활용
# : Series의 경우 문자열 인덱스를 가질 수 있기 떄문에 이름(문자열)을 통해서도 개별 데이터에 접근 가능
#  - 인덱스가 문자로 지정된 경우에는 위치(숫자)를 동시에 사용가능
#  - 문자인덱스를 이용하여 슬라이싱하는 경우 마지막 값을 포함

In [50]:
series = pd.Series([1,2,3,4,5], index=['A', 'B', 'C', 'D', 'E'])
series

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [51]:
# 첫번째(A) 항목 선택
series['A']

1

In [52]:
# 첫번째(A)부터 네번째(D) 항목 선택
series['A':'D'] #series[0:4]

A    1
B    2
C    3
D    4
dtype: int64

In [55]:
# 마지막(E) 항목 선택
series['E'], series[-1], series[len(series)-1]

/var/folders/06/r2dtrmr16vqfn420q_zltnpw0000gn/T/ipykernel_32514/1235485597.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series['E'], series[-1]

(5, 5)

In [56]:
# DataFrame 인덱싱과 슬라이싱
# - DataFrame에서 인덱싱과 슬라이싱은 다르게 동작함
# - 인덱싱의 경우 열 단위 선택을, 슬라이싱의 경우 행 단위 선택

In [57]:
df = pd.DataFrame([[1,2],[3,4],[5,6]], index=['A', 'B', 'C'], columns=[1,2])
df

   1  2
A  1  2
B  3  4
C  5  6

In [58]:
# A열의 1번 항목 선택
df[1]['A']

1

In [60]:
# A부터 B행까지 선택
df['A':'B']

   1  2
A  1  2
B  3  4

In [62]:
# B부터 C행까지 2번열 선택
df[2]['B':'C']

B    4
C    6
Name: 2, dtype: int64

In [61]:
df['B':'C'][2]

B    4
C    6
Name: 2, dtype: int64

In [ ]:
# - 조건인덱싱 : 여러개의 행을 가지고 오고 싶은 경우
#             Boolean Series인 경우 True값을 가지는 인덱스를 기반으로 행 선택
#             Boolean DataFrame인 경우 True값을 가지는 행인덱스와 열인덱스를 기반으로 선택하며, 
#             False값을 가지는 위치는 NaN으로 설정됨
# - 팬시인덱싱 : 여러개의 열을 가지고 오고 싶은 경우 (원하는 컬럼을 list로 묶어서 인덱싱)

In [ ]:
# 데이터가 짝수인 경우 인덱싱
series[series%2==0]

In [63]:
df[2]['B'] = 5
df

   1  2
A  1  2
B  3  5
C  5  6

In [64]:
df[df%2==0]

    1    2
A NaN  2.0
B NaN  NaN
C NaN  6.0

In [66]:
# True False에서는 True인 값만 가져옴
blist = [True, False, False] # A만 true인 경우
df[blist]

   1  2
A  1  2

In [67]:
bseries = pd.Series([True, False, False], index=['C', 'B', 'A'])
df[bseries]

/var/folders/06/r2dtrmr16vqfn420q_zltnpw0000gn/T/ipykernel_32514/471636472.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[bseries]

   1  2
C  5  6

In [68]:
# 2번열의 값이 짝수인 경우 인덱싱
df[df[2]%2==0]

   1  2
A  1  2
C  5  6

In [70]:
df[3] = [4,5,6]
df['sum'] = df.sum(axis=1) # 열과 열끼리 더함
df

   1  2  3  sum
A  1  2  4    7
B  3  5  5   13
C  5  6  6   17

In [71]:
# 1번과 2번열 인덱싱
df[[1,2]]

   1  2
A  1  2
B  3  5
C  5  6

In [76]:
# Indexer
# : - Pandas에서 데이터 선택은 기본적인 인덱싱과 슬라이싱보다는 Indexer를 이용하는 방법 권장
#     why? 기본 인덱싱, 슬라이싱으로 선택된 데이터는 값을 추가/수정 시 오류 발생 가능


#   - Pandas Indexer : loc, iloc, at, iat

#     * loc, at      :   이름을 기반으로 인덱싱
#     * iloc, iat    :   위치를 기반으로 인데싱 (i는 integer)
#     * at, iat      :   한개의 값만 반환

# < 문법 >
# dataframe.인덱서[행인덱스, 열인덱스]

In [77]:
# 기본 인덱싱과 슬라이싱 방법으로 선택된 데이터는 원본 데이터와 연결되지 않거나, 참조가 아닌 복사본을 반환하는 경우가 많습니다. 이로 인해 데이터를 수정하려고 할 때 예기치 않은 오류가 발생할 수 있습니다. 
# 데이터를 슬라이싱하여 subset에 할당했을 때, subset은 df['Age']의 복사본이 됩니다. 
# 이 복사본에 대해 값을 변경하려고 할 때 "SettingWithCopyWarning" 경고가 발생하고, 실제 원본 데이터는 수정되지 않을 수 있습니다. 
# 인덱서(indexer)를 사용하면 데이터가 참조되기 때문에 원본 데이터에 대해 직접 작업할 수 있습니다. 
# 인덱서를 사용하면 값 수정, 추가, 삭제 등의 작업이 안전하고 정확하게 수행합니다.

In [82]:
subset = df[[1,2]]
#subset[1]['A'] = 5 # 오류

In [ ]:
## loc 인덱서
# - 인덱싱 : dataframe.loc[행, 열]
# - 슬라이싱 : dataframe.loc[시작:끝, 시작:끝] (끝이 포함됨)
# - 이름(문자열)의 리스트나 슬라이싱
# - boolean리스트, 1차원배열, 시리즈 (데이터프레임은 불가)

In [83]:
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(4,3),
                  index=['A','B','C','D'],
                  columns=['X1','X2','X3'])
df

   X1  X2  X3
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11

In [84]:
df.loc[:'B',['X1','X3']]

   X1  X3
A   0   2
B   3   5

In [85]:
# A행 선택
df.loc['A']

X1    0
X2    1
X3    2
Name: A, dtype: int64

In [87]:
# X1열 선택
df.loc[:,'X1']

A    0
B    3
C    6
D    9
Name: X1, dtype: int64

In [92]:
# A와 C행, X1과 X2열 선택
df.loc[['A','C'],['X1', 'X2']]

   X1  X2
A   0   1
C   6   7

In [ ]:
# X1열의 항목이 짝수인 행의 X1과 X3열 선택
df.loc[df['X1'% 2 == 0],['X1','X3']

In [93]:
## iloc 인덱서
#  : iloc 인덱서를 사용하는 경우에는 행 또는 열 인덱스 다음과 같은 형식
#   - 위치 (정수)
#   - 위치 (정수)의 리스트나 슬라이싱
#   - boolean 리스트나, 1차원 배열(시리즈 불가)

# < 문법 >
# dataframe.iloc[행인덱스, 열인덱스]

In [94]:
df

   X1  X2  X3
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11

In [95]:
df.iloc[0,]

X1    0
X2    1
X3    2
Name: A, dtype: int64

In [ ]:
# df.iloc['A',] - 에러

In [101]:
# X1열 선택
df.iloc[:,0]

A    0
B    3
C    6
D    9
Name: X1, dtype: int64

In [103]:
# A와 C행, X1과 X2열 선택
df.iloc[[0,2],[0,1]]

   X1  X2
A   0   1
C   6   7

In [104]:
# X1열의 항목이 짝수인 행의 X1과 X3열 선택
# blist = list(df['X1']%2==0)
df.iloc[list(df['X1']%2==0), [0,2]]

   X1  X3
A   0   2
C   6   8

In [ ]:
## at, iat 인덱서
#  - at, iat 인덱서는 하나의 값만 가져옴
#  - 빠른 인덱싱 속도가 요구되는 경우 사용
#  - loc, iloc보다 at, iat이 소모시간이 적음

# < 문법 >
# dataframe.at[행인덱스, 열인덱스]
# dataframe.iat[행인덱스, 열인덱스]

In [105]:
df

   X1  X2  X3
A   0   1   2
B   3   4   5
C   6   7   8
D   9  10  11

In [106]:
%%time
df.loc['A', 'X1']

CPU times: user 154 μs, sys: 219 μs, total: 373 μs
Wall time: 389 μs

0

In [107]:
%%time
df.at['A', 'X1']

CPU times: user 65 μs, sys: 95 μs, total: 160 μs
Wall time: 164 μs

0

In [108]:
%%time
df.iloc[-1,-1]

CPU times: user 185 μs, sys: 487 μs, total: 672 μs
Wall time: 678 μs

11

In [109]:
%%time
df.iat[-1,-1]

CPU times: user 111 μs, sys: 22 μs, total: 133 μs
Wall time: 141 μs

11

In [ ]:
# Pandas 함수
# 1. info()
#    : DataFrame의 기본 정보
#      주로 데이터 개수, 데이터 타입을 동시에 확인할 때 사용
#      인덱스, 컬럼, 각 컬럼의 데이터 타입, 메모리 사용, 누락 데이터 개수등의 정보 제공

In [111]:
df = pd.DataFrame({'A':[1,2,3], 'B':[2,3,4]})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [112]:
ser = pd.Series([1,2,3])
ser.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes

In [ ]:
# 2. head(n)/tail(n)

In [ ]:
#첫행부터 2개의 데이터 조회
df.head(2)

In [ ]:
#끝행부터 2개의 데이터 조회
df.tail(2)

In [ ]:
# 3. value_counts(sort=True, ascending=False, normalize=False)
# Series에서 자주 쓰임
# 값의 개수를 계산하여 내림차순으로 정렬 후 결과 반환
# sort=False : 정렬하지 않고 반환
# ascending : 정렬기준, True=오름차순, False=내림차순으로 정렬
# normalize=True 값의 비율로 반환

In [113]:
ser = pd.Series(['A', 'B', 'B', 'C', 'A', 'B'])

In [114]:
ser.value_counts()

B    3
A    2
C    1
Name: count, dtype: int64

In [115]:
ser.value_counts(sort=False)

A    2
B    3
C    1
Name: count, dtype: int64

In [116]:
ser.value_counts(ascending=True)

C    1
A    2
B    3
Name: count, dtype: int64

In [117]:
ser.value_counts(normalize=True)

B    0.500000
A    0.333333
C    0.166667
Name: proportion, dtype: float64

In [ ]:
# 4. sort_values(by, ascending=True, inplace=False)
# by<컬럼명> : 특정컬럼을 기준으로 데이터 정렬
# ascendng : True=오름차순, False=내림차순으로 정렬
# inplace : 원본데이터 변경 여부, True=원본데이터를 변경

In [118]:
ser = pd.Series([1,2,3,4,5])
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [119]:
ser.sort_values()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# 내림차순으로 정렬
ser.sort_values(ascending=False)

In [120]:
df = pd.DataFrame({'A':[1,2,3], 'B':[2,3,4]})

In [121]:
# B열을 기준으로 내림차순 정렬
df.sort_values(by='B', ascending=False)

   A  B
2  3  4
1  2  3
0  1  2

In [122]:
df # 기존 값이 변경되지 않음

   A  B
0  1  2
1  2  3
2  3  4

In [123]:
# B열을 기준으로 내림차순 정렬한 데이터프레임으로 기존값 변경
df.sort_values(by='B', ascending=False, inplace=True)
df

   A  B
2  3  4
1  2  3
0  1  2

In [ ]:
# 5. sort_index(axis=0 or 1, ascending=True, inplace=False)
# 행(axis=0) 또는 열(axis=1) 인덱스를 오름차순 또는 내림차순으로 정렬
# 열(axis=1) 지정은 DataFrame에서만 가능

In [124]:
df

   A  B
2  3  4
1  2  3
0  1  2

In [125]:
# 행을 기준으로 오름차순 정렬
df.sort_index(axis=0, ascending=True)

   A  B
0  1  2
1  2  3
2  3  4

In [126]:
# 열을 기준으로 내림차순 정렬
df.sort_index(axis=1, ascending=False)

   B  A
2  4  3
1  3  2
0  2  1

In [ ]:
# 데이터 컬럼 명 변경
# * 전체 컬럼의 이름을 변경할 경우
# < 문법 >
# dataframe.column = <변경하고자 하는 컬럼 정보>
#  - DataFrame에서만 가능
#  - 변경하고자 하는 컬럼정보의 개수는 반드시 기존 컬럼의 개수와 동일해야 함

In [147]:
df = pd.DataFrame(np.random.randint(10,99,9).reshape(3,3))
df

    0   1   2
0  94  77  98
1  21  45  17
2  12  55  77

In [148]:
df.columns = list('ABC')
df

    A   B   C
0  94  77  98
1  21  45  17
2  12  55  77

In [ ]:
# * 특정 컬럼의 이름만 변경할 경우
# < 문법 > 
# dataframe.rename(columns={'변경전':'변경후'}, inplace)
# series.rename('변경후', inplace)

In [135]:
ser = pd.Series(np.arange(1,10))
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [136]:
# 컬럼명을 'A'로 변경하고 기존 데이터프레임을 변경하지 않음
ser.rename("A")

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: A, dtype: int64

In [137]:
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [149]:
# A컬럼명을 X1으로, B컬럼명을 X2로 변경하여 기존 데이터프레임 변경
df.rename(columns={'A':'X1', 'B':'X2'}, inplace=True)
df

   X1  X2   C
0  94  77  98
1  21  45  17
2  12  55  77

In [150]:
df.rename(index={0:'a'})

   X1  X2   C
a  94  77  98
1  21  45  17
2  12  55  77

In [ ]:
# 데이터 타입 변경

In [ ]:
# * astype(str or dict)
# - DataFrame의 전체 데이터 유형을 변환하거나 특정컬럼만 변경 가능
# - 전체 데이터 유형을 변환하고자 할 경우 변환하고자 하는 데이터 유형을 문자열로 지정
# - 특정 컬럼의 데이터 유형만 변경하고 싶은 경우 딕셔너리 형태로 지정

In [151]:
# 전체 데이터타입을 float로 변경
df.astype('float')

     X1    X2     C
0  94.0  77.0  98.0
1  21.0  45.0  17.0
2  12.0  55.0  77.0

In [140]:
df

    A   B   C
0  51  72  81
1  84  68  94
2  82  97  54

In [154]:
# X1컬럼의 데이터타입을 float로 변경
#df['X1'].astype('float') #둘 다 가능
df.astype({'X1':'float'})
# df.astype({'X1':'float'}).dtypes
# df['X1'].astype('float').dtypes

     X1  X2   C
0  94.0  77  98
1  21.0  45  17
2  12.0  55  77

In [158]:
df.loc[1,'D'] = 'a'

In [159]:
df

   X1  X2   C    D
0  94  77  98  NaN
1   a   a  17    a
2  12  55  77  NaN

In [160]:
# 데이터 타입을 숫자로 변환

In [ ]:
# - astype을 이용하여 숫자형으로 변경하고자 하는 경우 에러가 발생할 수 있음
#   숫자형으로 변경이 불가능한 데이터가 존재하는 경우 발생
# - pandas.to_numeric()을 이용하면 에러유형에 따라 변환방법을 지정 가능
#   errors='ignore' : 에러가 발생하지 않고 변경이 안됨
#   errors='raise' : 에러를 발생시킴 (기본값)
#   errors='coerce' : 에러가 발생한 데이터를 NaN으로 변환

In [162]:
ser = pd.Series([1,2,3,'a', 4, 'b'])
ser.astype('int') # 문자포함이기 때문에 에러발생

In [ ]:
pd.to_numeric(ser) # 에러

In [163]:
# 숫자로 변경하되, 에러는 무시
pd.to_numeric(ser, errors='ignore')

/var/folders/06/r2dtrmr16vqfn420q_zltnpw0000gn/T/ipykernel_32514/3318294325.py:2: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  pd.to_numeric(ser, errors='ignore')

0    1
1    2
2    3
3    a
4    4
5    b
dtype: object

In [164]:
#숫자로 변경하되, 에러인 경우 NaN으로 대체
pd.to_numeric(ser, errors='coerce')

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [ ]:
# 날짜 형식의 데이터 타입 변경
# < 문법 >
# panda.to_datetime(dataframe, format)

# - DataFrame의 컬럼명이 'year', 'month', 'day', 'hour', 'minute', 'second', 'ms', 'us', 'ns'와 같다면 
#   날짜 형식 데이터를 반환
# - 자동으로 합쳐져 datetime형식을 반환

In [166]:
date = pd.DataFrame({'year':[2022, 2021, 2020], 'month':[1, 7, 12], 'day':[1,5, 28]})
date

   year  month  day
0  2022      1    1
1  2021      7    5
2  2020     12   28

In [167]:
pd.to_datetime(date)

0   2022-01-01
1   2021-07-05
2   2020-12-28
dtype: datetime64[ns]

In [ ]:
# 날짜 범위 생성
# < 문법 >
# pandas.date_range(start, end, periods, freq)
# - 특정 날짜/시간 범위의 데이터를 생성가능
# - periods : 데이터의 개수
# - freq : 주기 ('YS', 'YE', 'MS', 'ME', 'd', 'min', 's')

In [168]:
# '20200101'부터 10개의 기간 만들기
pd.date_range('20200101', periods=10)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [169]:
# '20200101'부터 '20241231'까지 월별(초) 주기로 구간 만들기
pd.date_range('20200101', '20241231', freq='MS')

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01',
               '2020-05-01', '2020-06-01', '2020-07-01', '2020-08-01',
               '2020-09-01', '2020-10-01', '2020-11-01', '2020-12-01',
               '2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01',
               '2021-05-01', '2021-06-01', '2021-07-01', '2021-08-01',
               '2021-09-01', '2021-10-01', '2021-11-01', '2021-12-01',
               '2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
               '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [ ]:
# 데이터 삭제
# < 문법 > 
# dataframe.drop(labels, axis, inplace)
# - labels로 지정된 행(axis=0)또는 열(axis=1)이 삭제된 결과 반환
# - 삭제대상이 여러 개인 경우 행 또는 열 인덱스를 []로 묶어서 지정

In [171]:
df

   X1  X2   C    D
0  94  77  98  NaN
1   a   a  17    a
2  12  55  77  NaN

In [172]:
df.drop('D',axis=1)

   X1  X2   C
0  94  77  98
1   a   a  17
2  12  55  77

In [173]:
# 행인덱스가 1인 행 삭제
df.drop(1, axis=0)

   X1  X2   C    D
0  94  77  98  NaN
2  12  55  77  NaN

In [174]:
# 열인덱스가 X1, X2인 열을 삭제
df.drop(['X1', 'X2'], axis=1)

    C    D
0  98  NaN
1  17    a
2  77  NaN

In [ ]:
# 데이터 구간별 범주화
# < 문법 > 
# pandas.cut(x, bins, right, labels,..)
# - 연속 데이터를 구간별 범주화
# - x : 데이터
# - bins : 구간을 나누는 기준
# - right : 구간의 오른쪽 값 포함 여부
# - labels : 구간의 이름

In [175]:
ages = [0, 15, 10, 21, 23, 37, 31, 61, 20, 41, 32, 100]
bins = [0, 20, 35, 50, 65, 100]
labels = ['청소년', '청년', '중년', '장년', '노년']
cuts = pd.cut(ages, bins, labels=labels)
cuts

[NaN, '청소년', '청소년', '청년', '청년', ..., '장년', '청소년', '중년', '청년', '노년']
Length: 12
Categories (5, object): ['청소년' < '청년' < '중년' < '장년' < '노년']

In [176]:
cuts.value_counts()

청소년    3
청년     4
중년     2
장년     1
노년     1
Name: count, dtype: int64

In [178]:
# Pandas 통계함수
# 데이터에 대한 통계 계산을 Pandas 통계함수를 사용하여 통계값 산출 가능
# Pandas는 배열의 주어진 요소로 부터 최소, 최대, 평균, 분산, 표준편차 등을 찾는데 유용한 통계함수가 존재
# 통계함수는 배열에서 요소별로 작동하며 axis옵션을 통해 연산 방향을 지정할 수 있음
# axis=0 : 행과 행의 연산결과를 반환(기본값)
# axis=1 : 열과 열의 연산결과를 반환
# describe, sum, min, max, mean, count, std, var, prod, corr, argmin, argmax, cumsum, cumprod 등

In [ ]:
# 1. describe() 요약통계
# - 전반적인 기술통계 정보를 확인할 수 있음
# - 기본값으로 수치형(Numeric) 컬럼에 대한 통계표를 보여줌
#    count:데이터개수, mean:평균, std:표준편차,
#    min:최소값, 25%:1분위수(하위25%값), 50%:2분위수(중앙값), 75%:3분위수(상위25%값), max:최대값

In [ ]:
# colab에서 드라이브 읽어오기

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 시간대별 교통사고.csv파일 읽기
with open('/content/drive/MyDrive/LikeLion/!수업자료/시간대별 교통사고.csv',
          'r', encoding='EUC-KR') as f:
    df = pd.read_csv(f)

df

In [ ]:
df.describe()

In [ ]:
# 2. count() 데이터의 개수
#    NaN을 제외한 데이터의 개수 계산
# 전체 데이터
# dataframe.count()
# 단일 컬럼의 데이터
# dataframe['<컬럼명>'].count()

In [ ]:
# DataFrame 전체 데이터의 개수
df.count()

In [ ]:
# '사고건수' 컬럼의 데이터 개수
df['사고건수'].count()

In [ ]:
# 3. mean() 평균
# NaN을 제외한 데이터의 평균 계산
# 조건별 평균도 계산 가능
# 전체 데이터의 평균
# dataframe.mean()
# 컬럼의 평균
# dataframe['<컬럼명>'].mean()
# 조건별 평균(조건식에 맞는 컬럼 데이터의 평균)
# dataframe.loc[<조건식>, '<컬럼명>'].mean()

In [179]:
# NaN을 제외한 데이터의 평균 계산
# df.mean()

In [ ]:
# 컬럼의 평균
df.loc[:,'사고건수':].mean()

In [ ]:
# 조건별 평균
condition = (df['요일'] == '월')
df.loc[condition, '사고건수'].mean()

In [ ]:
# 4. skipna=True 옵션
# NaN의 값을 제외하고 기술통계함수를 실행
# skipna=False로 설정하면 NaN값이 있는 컬럼은 NaN으로 출력

In [ ]:
df_missing = pd.read_csv('/content/drive/MyDrive/missing_data_test .csv', encoding='EUC-KR')

In [ ]:
try:
  with open('/content/drive/MyDrive/missing_data_test .csv','r', encoding = 'EUC-KR') as f:
    df_missing = pd.read_csv(f)
    print('파일읽기 성공')
except:
    print('파일읽기 실패')

In [181]:
df_missing

In [ ]:
# skipna=True의 평균
df_missing.mean(skipna=True) # skipna = True NaN을 뺀 평균값 / False NaN이 있으면 NaN이다.

In [ ]:
# 밑의 함수들은 colab 사용(파일 볼 것)