## 결측치(Null, NaN, NA) 처리
- 결측치 처리는 대표적으로,
    - 결측치 제거
    - 평균값(mean), 중앙값(median), 빈도값(mode), 0으로 대체
    - 예측모델을 이용하여 대체 <br>
하는 방식이 주로 이루어짐
- 가장 쉽고 좋은 방법은 결측치가 포함된 행 또는 열을 삭제하는 것
    - 데이터가 많은 경우에만 사용가능하며, 데이터의 수가 충분하지 않은 경우 잘 사용하지 않음
- 결측치는 사전에 발생하지 않도록 조치하는 것이 좋음
- 결측치를 처리할 경우 도메인지식은 필수적이며, 결측치를 다른 값으로 대체할 경우 어떠한 값으로 할지에 대한 적절한 의사결정이 필요함

- Pandas의 경우 누락된 데이터를 나타내기 위해 np.nan이라는 값을 사용하며 계산에 포함되지 않음
    - Pandas의 경우 Null과 NA를 모두 NaN 형식으로 처리
    - 데이터가 NaN인 경우 `isna` 또는 `notna` 함수를 통해서만 비교 가능
    - 결측치를 삭제 : `dropna`
    - 결측치를 치환 : `fillna(<대체값>)`

In [25]:
import pandas as pd
import numpy as np

In [4]:
# 난수를 생성하여 음수인 경우 NaN, 양수인 경우 원래값을 가지도록 데이터프레임 생성
np.random.seed(0)
df = pd.DataFrame(np.random.randn(5,5), columns = ['A', 'B', 'C', 'D', 'E'])
df = df[df>0]
df

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
1       NaN  0.950088       NaN       NaN  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079       NaN  0.313068       NaN
4       NaN  0.653619  0.864436       NaN  2.269755

### `isna()`, `isnull()`
- Series 또는 DataFrame의 요소가 NaN과 같으면 True, 다르면 False 결과를 반환

In [5]:
df.isna()

       A      B      C      D      E
0  False  False  False  False  False
1   True  False   True   True  False
2  False  False  False  False  False
3  False  False   True  False   True
4   True  False  False   True  False

In [6]:
df.isnull()

       A      B      C      D      E
0  False  False  False  False  False
1   True  False   True   True  False
2  False  False  False  False  False
3  False  False   True  False   True
4   True  False  False   True  False

### `notna()`, `notnull()`
- Series 또는 DataFrame의 요소가 NaN과 같지 않으면 True, 같으면 False 결과를 반환

In [7]:
df.notna()

       A     B      C      D      E
0   True  True   True   True   True
1  False  True  False  False   True
2   True  True   True   True   True
3   True  True  False   True  False
4  False  True   True  False   True

In [8]:
df.notnull()

       A     B      C      D      E
0   True  True   True   True   True
1  False  True  False  False   True
2   True  True   True   True   True
3   True  True  False   True  False
4  False  True   True  False   True

### 결측치 개수
- NaN을 비교하는 함수와 행 또는 열의 합을 sum함수를 이용하여 행별 또는 열별 결측치의 개수 계산 가능

In [10]:
# 행별 결측치 개수
df.isna().sum(axis=1)

0    0
1    3
2    0
3    2
4    2
dtype: int64

In [17]:
df

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
1       NaN  0.950088       NaN       NaN  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079       NaN  0.313068       NaN
4       NaN  0.653619  0.864436       NaN  2.269755

In [11]:
# 열별 결측치 개수 # 행 기준으로 연산하기 때문에 axis=0
df.isna().sum(axis=0)

A    2
B    0
C    2
D    2
E    1
dtype: int64

In [13]:
# 결측치 총 개수
df.isna().sum().sum()

7

In [14]:
# 총 column의 개수가 5개라는것을 알 수 있어 non-null Count로 그 수를 계산할 수 있다.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       5 non-null      float64
 2   C       3 non-null      float64
 3   D       3 non-null      float64
 4   E       4 non-null      float64
dtypes: float64(5)
memory usage: 332.0 bytes

### `dropna(axis, how, thresh, inplace)` 결측치 삭제
- 결측치를 삭제
- `axis` : 행 또는 열의 결측치를 삭제
- `how` : 삭제방법 설정
    - `any` : 1개라도 NaN이 존재하는 행 또는 열을 삭제(기본값)
    - `all` : 모든 NaN인 행 또는 열을 삭제
- `thresh` : 삭제기준 설정
    - NaN가 아닌 데이터의 최소개수를 지정
- `inplace` : 원본데이터 변경 여부 지정

In [15]:
# 결측치가 있는 1개라도 있는 행 삭제
df.dropna(axis=0, how='any')

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
2  0.144044  1.454274  0.761038  0.121675  0.443863

In [16]:
# 결측치가 있는 1개라도 있는 열 삭제
df.dropna(axis=1, how='any')

          B
0  0.400157
1  0.950088
2  1.454274
3  1.494079
4  0.653619

In [18]:
# 결측치가 있는 3개이상인 행 삭제
df.dropna(axis=0,thresh=3)

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079       NaN  0.313068       NaN
4       NaN  0.653619  0.864436       NaN  2.269755

### `fillna(value, method, inplace)` 결측치 대체
- 결측치값을 치환
- 만약 1개의 값이 지정된 경우 모든 결측치를 해당 값으로 치환
- NaN을 제외한 각 컬럼의 대체값을 계산 후 각 컬럼의 평균, 중앙값, 최빈값으로 결측치 대체
- 시계열 데이터의 경우 보간방법(method)을 설정할 수 있음
    - `ffill` : 결측치가 발생한 이전 값으로 대체
    - `bfill` : 결측치가 발생한 이후 값으로 대체

In [20]:
# 0으로 채우기
df.fillna(0)

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
1  0.000000  0.950088  0.000000  0.000000  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079  0.000000  0.313068  0.000000
4  0.000000  0.653619  0.864436  0.000000  2.269755

In [21]:
# 평균으로 채우기
df.fillna(df.mean())

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
1  0.747257  0.950088  0.868071  0.891879  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079  0.868071  0.313068  1.247944
4  0.747257  0.653619  0.864436  0.891879  2.269755

In [24]:
# 결측치가 발생한 이전 값으로 대체
df.fillna(method='ffill')

<ipython-input-24-f324cd8c4b7d>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

          A         B         C         D         E
0  1.764052  0.400157  0.978738  2.240893  1.867558
1  1.764052  0.950088  0.978738  2.240893  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863
3  0.333674  1.494079  0.761038  0.313068  0.443863
4  0.333674  0.653619  0.864436  0.313068  2.269755

## Grouping
- 그룹분석은 자료를 집단별로 나누어 그룹 함수를 적용한 분석 방법
    - 빈도 분석이 그룹별 빈도만을 산출하는 것에 비하여 그룹분석은 빈도는 물로 그룹별 특정값에 대한 합계, 평균, 표준편차, 중앙값, 최대값, 최소값 등과 같은 결과를 산출
- `groupby`함수를 이용하여 그룹별 집계 결과를 계산
    - `groupby`는 데이터를 그룹별로 분할하고(Splitting), 각 그룹별로 집계함수를 적용(Applying) 후 결과를 하나로 합친(Combining) 결과를 반환함
    - 그룹기준, 집계대상, 집계방법을 지정
- `groupby`는 다양한 형태로 사용가능함
```
# 그룹기준이 1개인 경우
dataframe.groupby(그룹기준)
# 그룹기준이 N개인 경우
dataframe.groupby([그룹기준1,..., 그룹기준N])
# 집계대상이 1개인 경우
dataframe.groupby(그룹기준)[집계대상]
# 집계대상이 N인경우
dataframe.groupby(그룹기준)[[집계대상1,...,집계대상N]]
# 집계함수가 1개인 경우
dataframe.groupby(그룹기준)[집계대상].집계함수()
# 집계함수가 N개인 겨우
dataframe.groupby(그룹기준).agg([집계함수1,...,집계함수N])
```
    - 1개를 지정하는 경우 해당 이름(주로 컬럼명)을 지정하고, 여러개를 지정하고 싶은 경우 이름을 묶어서 저장함

In [26]:
df = pd.DataFrame({
    'X1': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'],
    'X2': [3, 1, 0, 1, 7, 3, 2, 1, 3],
    'X3': [1, 2, 5, 6, 2, 3, 4, 1, 2]
    })
df

  X1  X2  X3
0  A   3   1
1  A   1   2
2  A   0   5
3  B   1   6
4  B   7   2
5  B   3   3
6  C   2   4
7  C   1   1
8  C   3   2

In [27]:
# X1를 기준으로 그룹화하여 sum을 계산
df.groupby('X1').sum()

    X2  X3
X1
A    4   8
B   11  11
C    6   7

In [28]:
# X1를 기준으로 X2에 대해 sum을 계산
df.groupby('X1')['X2'].sum()

X1
A     4
B    11
C     6
Name: X2, dtype: int64

In [30]:
# x1를 기준으로 x2와 x3에 대해 sum을 계산
df.groupby('X1')[['X2','X3']].sum()

    X2  X3
X1
A    4   8
B   11  11
C    6   7

In [31]:
# x1를 기준으로 그룹화하여 sum을 계산
df.groupby('X1').agg('sum')

    X2  X3
X1
A    4   8
B   11  11
C    6   7

In [32]:
# x1를 기준으로 그룹화하여 sum과 mean을 계산
df.groupby('X1').agg(['sum','mean'])

    X2  X3
X1
A    4   8
B   11  11
C    6   7

## Pivoting
- Excel의 피벗테이블기능을 동일하게 Pandas에서 사용가능
- 데이터를 보다 빠르고 쉽게 분석 가능
- 행, 열 방향으로 필드를 재배치해 데이터를 한눈에 보기가 용이함
- 행으로만 지정가능한 groupby와 다르게 Pivot의 경우 열로도 지정이 가능함
- `pivot_table(values, index, columns, aggfunc, fill_value)`
    - `values` : 집계하려는 열의 Label 혹은 Label 리스트
    - `index` : 피벗테이블 행의 그룹으로 묶을 열의 Label이나 그룹 키
    - `columns` : 피벗테이블 열의 그룹으로 묶을 열의 Label이나 그룹 키
    - `aggfunc` : 집계함수나 함수리스트 (기본값은 mean)
    - `fill_value` : 누락된값의 대체값

In [33]:
df['D'] = ['X', 'X', 'Y', 'X', 'Y', 'X', 'X', 'Y', 'X']
df

  X1  X2  X3  D
0  A   3   1  X
1  A   1   2  X
2  A   0   5  Y
3  B   1   6  X
4  B   7   2  Y
5  B   3   3  X
6  C   2   4  X
7  C   1   1  Y
8  C   3   2  X

In [35]:
# 행을 x1으로, 열을 D로 하는 그룹의 'x2', 'x3'컬럼의 합계
df.pivot_table(index='X1', columns='D', values = ['X2', 'X3'], aggfunc='sum')

   X2    X3
D   X  Y  X  Y
X1
A   4  0  3  5
B   4  7  9  2
C   5  1  6  1

## Merge - 연결
- 분석의 규모가 커지게 되면 여러개의 데이터 테이블을 이용
    - 하나의 테이블에 모든 데이터를 기록하는 것은 좋지 않기 때문
- 데이터분석을 위해서는 여러개로 분할된 데이터 테이블을 하나로 만들어서 분석하는 것이 중요함
- Pandas의 경우 DataFrame과 DataFrame을 연결 또는 병합할 수 있음
    - `concat()` : 단순히 DataFrame을 연결(인덱스기준)
    - `merge()` : 특정한 기준으로 DataFrame을 연결(열의 값 기준)

### `pandas.concat()`
- 단순히 DataFrame을 연결하는 것으로 인덱스값이 중복될 수 있음

```
pandas.concat([dataframe,...dataframe], axis, join, ignore_index)
```
- `axis`
    - 상하연결(axis=0)
    - 좌우연결(axis=1)
- `join`
    - 동일한 이름을 가지는 인덱스가 없는 NaN값으로 대체(join='outer')(기본값)
    - 동일한 이름을 가지는 인덱스만 연결(join='inner')
- `ignore_index`
    - 기존의 인덱스를 무시하고 연결(ignore=True)

In [36]:
df1 = pd.DataFrame({
    'K' : ['K0', 'K1', 'K2'],
    'X1': ['A', 'B', 'C'],
    'X2': [1, 2, 3]
})
df1

    K X1  X2
0  K0  A   1
1  K1  B   2
2  K2  C   3

In [37]:
df2 = pd.DataFrame({
    'K' : ['K1', 'K2', 'K3'],
    'X2': ['B', 'A', 'D'],
    'X3': [4, 5, 6]
})
df2

    K X2  X3
0  K1  B   4
1  K2  A   5
2  K3  D   6

In [40]:
# 위아래로 합치기
pd.concat([df1,df2],axis=0)

    K   X1 X2   X3
0  K0    A  1  NaN
1  K1    B  2  NaN
2  K2    C  3  NaN
0  K1  NaN  B  4.0
1  K2  NaN  A  5.0
2  K3  NaN  D  6.0

In [41]:
# 동일한 인덱스만 위아래로 합치기
pd.concat([df1,df2], axis=0, join='inner')

    K X2
0  K0  1
1  K1  2
2  K2  3
0  K1  B
1  K2  A
2  K3  D

In [42]:
df1, df2

(    K X1  X2
 0  K0  A   1
 1  K1  B   2
 2  K2  C   3,
     K X2  X3
 0  K1  B   4
 1  K2  A   5
 2  K3  D   6)

In [44]:
# 좌우로 합치기
pd.concat([df1,df2],axis=1)

    K X1 X2   K X2  X3
0  K0  A  1  K1  B   4
1  K1  B  2  K2  A   5
2  K2  C  3  K3  D   6

In [46]:
# 인덱스를 무시하고 좌우로 합치기
pd.concat([df1,df2],axis=1,ignore_index=True)

    0  1  2   3  4  5
0  K0  A  1  K1  B  4
1  K1  B  2  K2  A  5
2  K2  C  3  K3  D  6

### `pandas.merge()`
- 두 DataFrame의 공통 열 혹은 인덱스를 기준으로 두 DataFrame을 병합

```
pandas.merge(on, how)
```
- `on` : 기준이 되는 열, 행의 데이터를 키(Key)라고 하며, 병합기준이 될 컬럼을 on으로 설정
- `how` : 결합 방법
    - `inner` : 키가 중복되어 존재하는 경우만 결합
    - `outer` : 동일한 키가 없는 경우 NaN으로 대체하여 결합
    - `left` : 왼쪽 DataFrame의 키를 기준으로 결합
    - `right` : 오른쪽 DataFrame의 키를 기준으로 결합

In [47]:
df1, df2

(    K X1  X2
 0  K0  A   1
 1  K1  B   2
 2  K2  C   3,
     K X2  X3
 0  K1  B   4
 1  K2  A   5
 2  K3  D   6)

In [48]:
# K열의 값이 공통이 되는 행만 결합
pd.merge(df1,df2,on='K',how='inner')

    K X1  X2_x X2_y  X3
0  K1  B     2    B   4
1  K2  C     3    A   5

In [52]:
# K열의 값이 공통이 되지 않는 값을 NaN로 결합
pd.merge(df1,df2,on='K', how='outer')

    K   X1  X2_x X2_y   X3
0  K0    A   1.0  NaN  NaN
1  K1    B   2.0    B  4.0
2  K2    C   3.0    A  5.0
3  K3  NaN   NaN    D  6.0

In [53]:
# 왼쪽 데이터프레임(df1)으로 K열의 값을 결합
pd.merge(df1, df2, on='K', how='left')

    K X1  X2_x X2_y   X3
0  K0  A     1  NaN  NaN
1  K1  B     2    B  4.0
2  K2  C     3    A  5.0

In [54]:
# 오른쪽 데이터프레임(df2)으로 K열의 값을 결합
pd.merge(df1, df2, on='K', how='right')

    K   X1  X2_x X2_y  X3
0  K1    B   2.0    B   4
1  K2    C   3.0    A   5
2  K3  NaN   NaN    D   6