In [13]:
import pandas as pd
df_2023 = pd.read_csv('/content/WHR2023.csv')

In [14]:
df_2023.head()

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110

In [12]:
one.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [16]:
a = pd.read_excel('/content/WHR20_DataForFigure2.1.xls')
a.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [18]:
b= pd.read_csv('/content/WHR_2020.csv')
b.head()

,country,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [23]:
# 숫자형 열만 선택
numeric_columns = b.select_dtypes(include=['float64', 'int64']).columns

# 숫자형 열들 간의 상관계수 계산
correlation_matrix = b[numeric_columns].corr()

In [24]:
correlation_matrix

,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
happiness_score,1.000000,0.775374,0.765001,0.770316,0.590597,0.069043,0.418305
gdp_per_capita,0.775374,1.000000,0.781814,0.848469,0.419019,-0.118399,0.334729
social_support,0.765001,0.781814,1.000000,0.742744,0.478863,-0.056780,0.210530
healthy_life_expectancy,0.770316,0.848469,0.742744,1.000000,0.448846,-0.071852,0.353841
freedom_to_make_life_choices,0.590597,0.419019,0.478863,0.448846,1.000000,0.253721,0.420145
generosity,0.069043,-0.118399,-0.056780,-0.071852,0.253721,1.000000,0.278480
perceptions_of_corruption,0.418305,0.334729,0.210530,0.353841,0.420145,0.278480,1.000000

In [25]:
a.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [29]:
# 'country'별로 그룹화하여 상관계수 계산
country_corr = b.groupby('country')[numeric_columns].corr()
country_corr['happiness_score']

country
Afghanistan  happiness_score                NaN
             gdp_per_capita                 NaN
             social_support                 NaN
             healthy_life_expectancy        NaN
             freedom_to_make_life_choices   NaN
                                             ..
Zimbabwe     social_support                 NaN
             healthy_life_expectancy        NaN
             freedom_to_make_life_choices   NaN
             generosity                     NaN
             perceptions_of_corruption      NaN
Name: happiness_score, Length: 1071, dtype: float64

In [31]:
# 숫자형 열만 선택
numeric_columns = b.select_dtypes(include=['float64', 'int64']).columns

# 전체 데이터에 대해 상관계수 계산
correlation_matrix = b[numeric_columns].corr()

# 'happiness_score'와 다른 변수들 간의 상관계수 추출
correlation_matrix['happiness_score']

happiness_score                 1.000000
gdp_per_capita                  0.775374
social_support                  0.765001
healthy_life_expectancy         0.770316
freedom_to_make_life_choices    0.590597
generosity                      0.069043
perceptions_of_corruption       0.418305
Name: happiness_score, dtype: float64

In [32]:
b.head()

,country,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.8087,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857
1,Denmark,Western Europe,7.6456,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260
2,Switzerland,Western Europe,7.5599,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946
3,Iceland,Western Europe,7.5045,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541
4,Norway,Western Europe,7.4880,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101

In [ ]:
# 결과적으로 년도별 비교를 위해 9개의 컬럼만 비교하기로 하였다.

In [3]:
import pandas as pd
df_2022 = pd.read_csv('/content/WHR_2022.csv')
df_2022.head()

,country,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.821,1.892,1.258,0.775,0.736,0.109,0.534
1,Denmark,Western Europe,7.636,1.953,1.243,0.777,0.719,0.188,0.532
2,Iceland,Western Europe,7.557,1.936,1.320,0.803,0.718,0.270,0.191
3,Switzerland,Western Europe,7.512,2.026,1.226,0.822,0.677,0.147,0.461
4,Netherlands,Western Europe,7.415,1.945,1.206,0.787,0.651,0.271,0.419

In [6]:
# 'year' 컬럼 추가하고 값 모든 값 2022로 설정
df_2022['year'] = 2022

In [9]:
# 결과 확인
df_2022.head()  # 데이터 일부 출력

,country,region,happiness_score,gdp_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,year
0,Finland,Western Europe,7.821,1.892,1.258,0.775,0.736,0.109,0.534,2022
1,Denmark,Western Europe,7.636,1.953,1.243,0.777,0.719,0.188,0.532,2022
2,Iceland,Western Europe,7.557,1.936,1.320,0.803,0.718,0.270,0.191,2022
3,Switzerland,Western Europe,7.512,2.026,1.226,0.822,0.677,0.147,0.461,2022
4,Netherlands,Western Europe,7.415,1.945,1.206,0.787,0.651,0.271,0.419,2022

In [11]:
df_2022.to_csv('/content/WHR_2022_year.csv', index=False)